branches:
  only:
    - develop
    - master

language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

install:
  - composer update ${COMPOSER_ARGS} --no-interaction

script:
  - vendor/bin/phpunit --verbose

sudo: false
